/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(alpbbheader_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ecc826681ab36e1629cf1b9c5f9b4942)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/alpbbheader_bb.h>
// pydoc.h is automatically generated in the build directory
#include <alpbbheader_bb_pydoc.h>

void bind_alpbbheader_bb(py::module& m)
{

    using alpbbheader_bb    = ::gr::atsc3::alpbbheader_bb;


    py::class_<alpbbheader_bb, gr::block, gr::basic_block,
        std::shared_ptr<alpbbheader_bb>>(m, "alpbbheader_bb", D(alpbbheader_bb))

        .def(py::init(&alpbbheader_bb::make),
           py::arg("framesize"),
           py::arg("rate"),
           py::arg("llsmode"),
           py::arg("llscount"),
           D(alpbbheader_bb,make)
        )
        



        ;




}








