/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bch_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(059766eebc1aca2f9db0f4e699b80554)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/bch_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bch_bb_pydoc.h>

void bind_bch_bb(py::module& m)
{

    using bch_bb    = ::gr::atsc3::bch_bb;


    py::class_<bch_bb, gr::block, gr::basic_block,
        std::shared_ptr<bch_bb>>(m, "bch_bb", D(bch_bb))

        .def(py::init(&bch_bb::make),
           py::arg("framesize"),
           py::arg("rate"),
           D(bch_bb,make)
        )
        



        ;




}








