/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyclicprefixer_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(55a090c4fb5d2c334630e16f1f8dcd5a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/cyclicprefixer_cc.h>
// pydoc.h is automatically generated in the build directory
#include <cyclicprefixer_cc_pydoc.h>

void bind_cyclicprefixer_cc(py::module& m)
{

    using cyclicprefixer_cc    = ::gr::atsc3::cyclicprefixer_cc;


    py::class_<cyclicprefixer_cc, gr::block, gr::basic_block,
        std::shared_ptr<cyclicprefixer_cc>>(m, "cyclicprefixer_cc", D(cyclicprefixer_cc))

        .def(py::init(&cyclicprefixer_cc::make),
           py::arg("fftsize"),
           py::arg("numpayloadsyms"),
           py::arg("numpreamblesyms"),
           py::arg("guardinterval"),
           py::arg("flmode"),
           py::arg("flen"),
           py::arg("vlength"),
           D(cyclicprefixer_cc,make)
        )
        



        ;




}








