/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(freqinterleaver_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f359678aef9c613316006b849eee545a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/freqinterleaver_cc.h>
// pydoc.h is automatically generated in the build directory
#include <freqinterleaver_cc_pydoc.h>

void bind_freqinterleaver_cc(py::module& m)
{

    using freqinterleaver_cc    = ::gr::atsc3::freqinterleaver_cc;


    py::class_<freqinterleaver_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<freqinterleaver_cc>>(m, "freqinterleaver_cc", D(freqinterleaver_cc))

        .def(py::init(&freqinterleaver_cc::make),
           py::arg("fftsize"),
           py::arg("numpayloadsyms"),
           py::arg("numpreamblesyms"),
           py::arg("guardinterval"),
           py::arg("pilotpattern"),
           py::arg("firstsbs"),
           py::arg("mode"),
           py::arg("cred"),
           py::arg("paprmode"),
           D(freqinterleaver_cc,make)
        )
        



        ;




}








