/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ldmcombiner_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(358d914045f73b771b673e4103854dd6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/ldmcombiner_cc.h>
// pydoc.h is automatically generated in the build directory
#include <ldmcombiner_cc_pydoc.h>

void bind_ldmcombiner_cc(py::module& m)
{

    using ldmcombiner_cc    = ::gr::atsc3::ldmcombiner_cc;


    py::class_<ldmcombiner_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ldmcombiner_cc>>(m, "ldmcombiner_cc", D(ldmcombiner_cc))

        .def(py::init(&ldmcombiner_cc::make),
           py::arg("level"),
           D(ldmcombiner_cc,make)
        )
        



        ;




}








