/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ldmframemapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(00ee7b7db6a77e2d721adb4ba08bb26b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/ldmframemapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <ldmframemapper_cc_pydoc.h>

void bind_ldmframemapper_cc(py::module& m)
{

    using ldmframemapper_cc    = ::gr::atsc3::ldmframemapper_cc;


    py::class_<ldmframemapper_cc, gr::block, gr::basic_block,
        std::shared_ptr<ldmframemapper_cc>>(m, "ldmframemapper_cc", D(ldmframemapper_cc))

        .def(py::init(&ldmframemapper_cc::make),
           py::arg("framesize"),
           py::arg("rate"),
           py::arg("constellation"),
           py::arg("fftsize"),
           py::arg("numpayloadsyms"),
           py::arg("numpreamblesyms"),
           py::arg("guardinterval"),
           py::arg("pilotpattern"),
           py::arg("pilotboost"),
           py::arg("firstsbs"),
           py::arg("fimode"),
           py::arg("timode"),
           py::arg("tidepth"),
           py::arg("fecmode"),
           py::arg("paprmode"),
           py::arg("cred"),
           py::arg("l1bmode"),
           py::arg("l1dmode"),
           D(ldmframemapper_cc,make)
        )
        



        ;




}








