/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(paprtr_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(030f7f489d443fa0dbf3a82c06cc7499)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/paprtr_cc.h>
// pydoc.h is automatically generated in the build directory
#include <paprtr_cc_pydoc.h>

void bind_paprtr_cc(py::module& m)
{

    using paprtr_cc    = ::gr::atsc3::paprtr_cc;


    py::class_<paprtr_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<paprtr_cc>>(m, "paprtr_cc", D(paprtr_cc))

        .def(py::init(&paprtr_cc::make),
           py::arg("fftsize"),
           py::arg("numpayloadsyms"),
           py::arg("numpreamblesyms"),
           py::arg("pilotpattern"),
           py::arg("firstsbs"),
           py::arg("paprmode"),
           py::arg("cred"),
           py::arg("vclip"),
           py::arg("iterations"),
           py::arg("vlength"),
           D(paprtr_cc,make)
        )
        



        ;




}








