/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(subframemapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(897a1cf8f630e5cf3b29e3d34483e281)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/subframemapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <subframemapper_cc_pydoc.h>

void bind_subframemapper_cc(py::module& m)
{

    using subframemapper_cc    = ::gr::atsc3::subframemapper_cc;


    py::class_<subframemapper_cc, gr::block, gr::basic_block,
        std::shared_ptr<subframemapper_cc>>(m, "subframemapper_cc", D(subframemapper_cc))

        .def(py::init(&subframemapper_cc::make),
           py::arg("framesizeplp0"),
           py::arg("rateplp0"),
           py::arg("fecmodeplp0"),
           py::arg("constellationplp0"),
           py::arg("fftsizeplp0"),
           py::arg("numpayloadsymsplp0"),
           py::arg("numpreamblesyms"),
           py::arg("guardintervalplp0"),
           py::arg("pilotpatternplp0"),
           py::arg("pilotboostplp0"),
           py::arg("firstsbs"),
           py::arg("fimodeplp0"),
           py::arg("timodeplp0"),
           py::arg("tidepthplp0"),
           py::arg("tiblocksplp0"),
           py::arg("tifecblocksmaxplp0"),
           py::arg("tifecblocksplp0"),
           py::arg("llsmodeplp0"),
           py::arg("credplp0"),
           py::arg("misomodeplp0"),
           py::arg("framesizeplp1"),
           py::arg("rateplp1"),
           py::arg("fecmodeplp1"),
           py::arg("constellationplp1"),
           py::arg("fftsizeplp1"),
           py::arg("numpayloadsymsplp1"),
           py::arg("guardintervalplp1"),
           py::arg("pilotpatternplp1"),
           py::arg("pilotboostplp1"),
           py::arg("fimodeplp1"),
           py::arg("timodeplp1"),
           py::arg("tidepthplp1"),
           py::arg("tiblocksplp1"),
           py::arg("tifecblocksmaxplp1"),
           py::arg("tifecblocksplp1"),
           py::arg("llsmodeplp1"),
           py::arg("credplp1"),
           py::arg("misomodeplp1"),
           py::arg("flmode"),
           py::arg("flen"),
           py::arg("paprmode"),
           py::arg("l1bmode"),
           py::arg("l1dmode"),
           D(subframemapper_cc,make)
        )
        



        ;




}








