/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(subframemapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd833cd9798a572588bbf3b8b425c7e3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/subframemapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <subframemapper_cc_pydoc.h>

void bind_subframemapper_cc(py::module& m)
{

    using subframemapper_cc    = ::gr::atsc3::subframemapper_cc;


    py::class_<subframemapper_cc, gr::block, gr::basic_block,
        std::shared_ptr<subframemapper_cc>>(m, "subframemapper_cc", D(subframemapper_cc))

        .def(py::init(&subframemapper_cc::make),
           py::arg("framesizesub0"),
           py::arg("ratesub0"),
           py::arg("fecmodesub0"),
           py::arg("constellationsub0"),
           py::arg("fftsizesub0"),
           py::arg("numpayloadsymssub0"),
           py::arg("numpreamblesyms"),
           py::arg("guardintervalsub0"),
           py::arg("pilotpatternsub0"),
           py::arg("pilotboostsub0"),
           py::arg("firstsbs"),
           py::arg("fimodesub0"),
           py::arg("timodesub0"),
           py::arg("tidepthsub0"),
           py::arg("tiblockssub0"),
           py::arg("tifecblocksmaxsub0"),
           py::arg("tifecblockssub0"),
           py::arg("llsmodesub0"),
           py::arg("credsub0"),
           py::arg("misomodesub0"),
           py::arg("framesizesub1"),
           py::arg("ratesub1"),
           py::arg("fecmodesub1"),
           py::arg("constellationsub1"),
           py::arg("fftsizesub1"),
           py::arg("numpayloadsymssub1"),
           py::arg("guardintervalsub1"),
           py::arg("pilotpatternsub1"),
           py::arg("pilotboostsub1"),
           py::arg("fimodesub1"),
           py::arg("timodesub1"),
           py::arg("tidepthsub1"),
           py::arg("tiblockssub1"),
           py::arg("tifecblocksmaxsub1"),
           py::arg("tifecblockssub1"),
           py::arg("llsmodesub1"),
           py::arg("credsub1"),
           py::arg("misomodesub1"),
           py::arg("flmode"),
           py::arg("flen"),
           py::arg("paprmode"),
           py::arg("l1bmode"),
           py::arg("l1dmode"),
           D(subframemapper_cc,make)
        )
        



        ;




}








