/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tdmframemapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6f193167a04dd593f5f5d369fa5aa8ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc3/tdmframemapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <tdmframemapper_cc_pydoc.h>

void bind_tdmframemapper_cc(py::module& m)
{

    using tdmframemapper_cc    = ::gr::atsc3::tdmframemapper_cc;


    py::class_<tdmframemapper_cc, gr::block, gr::basic_block,
        std::shared_ptr<tdmframemapper_cc>>(m, "tdmframemapper_cc", D(tdmframemapper_cc))

        .def(py::init(&tdmframemapper_cc::make),
           py::arg("framesizeplp0"),
           py::arg("rateplp0"),
           py::arg("fecmodeplp0"),
           py::arg("constellationplp0"),
           py::arg("timodeplp0"),
           py::arg("tiblocksplp0"),
           py::arg("tifecblocksmaxplp0"),
           py::arg("tifecblocksplp0"),
           py::arg("framesizeplp1"),
           py::arg("rateplp1"),
           py::arg("fecmodeplp1"),
           py::arg("constellationplp1"),
           py::arg("timodeplp1"),
           py::arg("tiblocksplp1"),
           py::arg("tifecblocksmaxplp1"),
           py::arg("tifecblocksplp1"),
           py::arg("plpsplit"),
           py::arg("fftsize"),
           py::arg("numpayloadsyms"),
           py::arg("numpreamblesyms"),
           py::arg("guardinterval"),
           py::arg("pilotpattern"),
           py::arg("pilotboost"),
           py::arg("firstsbs"),
           py::arg("fimode"),
           py::arg("cred"),
           py::arg("flmode"),
           py::arg("flen"),
           py::arg("misomode"),
           py::arg("paprmode"),
           py::arg("l1bmode"),
           py::arg("l1dmode"),
           D(tdmframemapper_cc,make)
        )
        



        ;




}








